modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="dragonblockultimate"
    version="0.0.1"
    displayName="Dragon Block Ultimate"
    authors="Unknown"
    description='''
Dragon Ball Mod
'''

[[dependencies.dragonblockultimate]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.225,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragonblockultimate]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
